services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    networks:
      - beekeeper-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=db
      - DB_USER=beekeeper
      - DB_PASSWORD=honeypassword
      - DB_NAME=beekeeper_db
      - JWT_SECRET=ya10de096e8739623d865d249558f8e0bb94b43fd5280ffb7796f75e93d81b77b50d10da745d223c40a280b9054645119dcee4913c5be41a8a269a1ea0a5bfde3fb398e74afa1359bb23c93c9a45576b0cd8250dda89a1b396be7f7bcf078405de10f11fdcabcd16b41842886cf5ea6d798a17a0c23172f7971240fc6f946724ae9018d8dcc3b87e58e1d7cb2c50cddc5ada80a3925197c1e274501fa3803fdb29648c52154a33b66cfa2b486976f73796cb260e9461f462868b464e79666396a308e51401514a9e8ea20f303908a6b227cf6789c1ef8dff31b6ed0a1636f179ae9007970d1d4e035410c618100c24c2f42d56d09bc1acd4918637e8b21fab629
    networks:
      - beekeeper-network
    restart: on-failure

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=beekeeper_db
      - MYSQL_USER=beekeeper
      - MYSQL_PASSWORD=honeypassword
      - MYSQL_ROOT_PASSWORD=deadfred
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - beekeeper-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=deadfred
    depends_on:
      - db
    networks:
      - beekeeper-network

volumes:
  db-data:

networks:
  beekeeper-network:
    driver: bridge    